### ISSUE TITLE
阿希钱包于近日（09/27 or 09/28）上线测试的bug记录与修改

### ISSUE THREAD

**Issue by lbgod2222** [AschPlatform/asch-frontend#18]
跟踪：

- [x] 个人中心页面的锁仓页面结构（风格统一）#19

- [x] 页面resize右侧变型 #19 

- [x] 区块生产-注册受托人-弹窗 #19 

- [x] 投票-投票/删除-弹窗 #19 

- [x] 个人中心-按钮 #20

- [x] 转账-按钮 #20

- [x] 投票-按钮 #20

- [x] 区块生产-按钮 #20

- [x] 个人页面-锁仓二级密码样式修改 #21

- [x] 应用中心-详情 / 充值 弹窗样式优化， 表格样式优化 #21

- [x] 区块浏览-ID(blockDetail) / 生产者(用户详情) 弹窗优化 / 调整搜索框 #21

- [x] 应用中心-TAB栏出现细微间距 / 应用列表详情页 弹窗优化样式 #22 

- [x] 资产页面-所有交互栏的微调 #22 

- [x] 应用中心-应用列表/已安装列表 内容溢出 (10/09) 

- [x] 资产-我发行的资产-注销/发行/设置 弹窗样式/响应式问题 (10/09) 

- [x] 转账截断调整逻辑 (10/09)

- [x] 应用中心-应用列表-详情颜色/关闭按钮修复(10/09)

- [x] 首页加载出现的数据绑定前内容问题 （测试性提交）solution: 区块高度显Loading，时间隐藏

**Comment by lbgod2222** [comment]
细节问题（可即时修改），将在此仓库以issue提交/关闭方式来监视，
较大问题（耗时），将会在progress中立牌子

**Comment by lbgod2222** [comment]
跟踪：
- [个人中心页面的锁仓页面结构（风格统一） ]
- [页面resize右侧变型 ] 

- [ 区块生产-注册受托人-弹窗 ] 

- [投票-投票/删除-弹窗] 

- [个人中心-按钮 ]
